services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    environment:
      - REDIS_APPENDONLY=yes
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: postgres
    environment:  
      POSTGRES_PASSWORD: liveWell25
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: