services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    environment:
      - REDIS_APPENDONLY=yes
    restart: unless-stopped