services:
  redis:
    image: redis:7-alpine
    command: redis-server --save 60 1 --loglevel warning
    networks:
      - backend

  celery:
    build: .
    command: celery -A config worker --loglevel=info
    depends_on:
      - redis
    networks:
      - backend

  websocket:
    build: .
    command: uvicorn config.asgi:application --host 0.0.0.0 --port 9000
    depends_on:
      - redis
    networks:
      - backend