# Generated by Django 5.0.4 on 2025-08-09 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cre', '0001_initial'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffavailability',
            name='current_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.task'),
        ),
        migrations.AddField(
            model_name='staffavailability',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffshift',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_shifts', to='cre.branch'),
        ),
        migrations.AddField(
            model_name='staffshift',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cre.shift'),
        ),
        migrations.AddField(
            model_name='staffshift',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_shifts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='overtimerequest',
            name='staff_shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_requests', to='cre.staffshift'),
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['branch'], name='cre_menu_branch__d1e053_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together={('branch', 'name')},
        ),
        migrations.AddIndex(
            model_name='menucategory',
            index=models.Index(fields=['menu'], name='cre_menucat_menu_id_64a7dc_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['category'], name='cre_menuite_categor_f30d62_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='menuitem',
            unique_together={('name', 'category')},
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['branch', 'status', 'total_price'], name='cre_order_branch__262836_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='cre_orderit_order_i_a0031e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='regionorstate',
            unique_together={('name', 'country', 'type')},
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('name', 'region_or_state')},
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['username'], name='cre_customu_usernam_8c2e2a_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='cre_customu_email_778d9d_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['phone_number'], name='cre_customu_phone_n_374a9c_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['status'], name='cre_customu_status_f07fd9_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['role'], name='cre_customu_role_d424f6_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['r_val'], name='cre_customu_r_val_5202d1_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['timezone'], name='cre_customu_timezon_9a0984_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['preferred_language'], name='cre_customu_preferr_0fb757_idx'),
        ),
        migrations.AddIndex(
            model_name='sequencecounter',
            index=models.Index(fields=['branch', 'sequence_type'], name='cre_sequenc_branch__83d9c6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sequencecounter',
            unique_together={('branch', 'sequence_type')},
        ),
        migrations.AddIndex(
            model_name='shiftpattern',
            index=models.Index(fields=['branch', 'active_from', 'active_until'], name='cre_shiftpa_branch__c7d521_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftpattern',
            index=models.Index(fields=['roles'], name='roles_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftpattern',
            index=models.Index(fields=['users'], name='users_idx'),
        ),
        migrations.AddConstraint(
            model_name='shiftpattern',
            constraint=models.CheckConstraint(check=models.Q(('roles__len__gt', 0), ('users__len__gt', 0), _connector='OR'), name='at_least_one_target'),
        ),
        migrations.AddIndex(
            model_name='shiftswaprequest',
            index=models.Index(fields=['initiator', 'status'], name='cre_shiftsw_initiat_99d4d9_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftswaprequest',
            index=models.Index(fields=['counterparty', 'status'], name='cre_shiftsw_counter_db41fb_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftswaprequest',
            index=models.Index(fields=['desired_date'], name='cre_shiftsw_desired_fe9fb3_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftswaprequest',
            index=models.Index(fields=['accepted_at'], name='cre_shiftsw_accepte_5d399c_idx'),
        ),
        migrations.AddIndex(
            model_name='staffshift',
            index=models.Index(fields=['user', 'start_datetime', 'end_datetime'], name='cre_staffsh_user_id_47e8ac_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='staffshift',
            unique_together={('user', 'shift', 'date')},
        ),
    ]
