# Generated by Django 5.0.4 on 2024-12-05 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRE', '0002_alter_country_continent_alter_country_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='created_by',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='created_by',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('company_admin', 'Company Admin'), ('restaurant_owner', 'Restaurant Owner'), ('country_manager', 'Country Manager'), ('restaurant_manager', 'Restaurant Manager'), ('shift_leader', 'Shift Leader'), ('cook', 'Cook'), ('delivery_man', 'Delivery Man'), ('cashier', 'Cashier'), ('utility_worker', 'Utility Worker'), ('cleaner', 'Cleaner'), ('food_runner', 'Food Runner')], max_length=30, null=True),
        ),
    ]
