# Generated by Django 5.0.4 on 2025-03-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRE', '0003_alter_customuser_city_alter_customuser_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending schedule'), ('active', 'Active'), ('suspended', 'Suspended'), ('on_leave', 'On Leave')], default='pending', max_length=20, null=True),
        ),
    ]
