# Generated by Django 5.0.4 on 2024-12-06 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRE', '0003_branch_created_by_restaurant_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('pending', 'Pending Approval')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='CRE.company'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='restaurants',
            field=models.ManyToManyField(blank=True, related_name='employees', to='CRE.restaurant'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='region_or_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='CRE.regionorstate'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('pending', 'Pending Approval')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='created_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='created_company', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[(1, 'Company Admin'), (2, 'Restaurant Owner'), (3, 'Country Manager'), (4, 'Restaurant Manager'), (5, 'Shift Leader'), (6, 'Cashier'), (7, 'Cook'), (8, 'Food Runner'), (9, 'Cleaner'), (10, 'Delivery Man'), (11, 'Utility Worker')], max_length=30, null=True),
        ),
    ]
