# Generated by Django 5.0.4 on 2025-09-29 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cre', '0004_branch_contact_email_branch_contact_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='cre.restaurant'),
        ),
    ]
