# Generated by Django 5.0.4 on 2025-04-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRE', '0004_alter_customuser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(blank=True, choices=[('inactive', 'Inactive'), ('pending', 'Pending schedule'), ('active', 'Active'), ('suspended', 'Suspended'), ('on_leave', 'On Leave')], default='pending', max_length=20, null=True),
        ),
    ]
