# Generated by Django 5.0.4 on 2024-12-12 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRE', '0005_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='CRE.company'),
        ),
    ]
