# Generated by Django 5.0.4 on 2025-05-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRE', '0006_remove_country_language_branch_default_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='timezone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
