# Generated by Django 5.0.4 on 2024-12-13 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRE', '0006_alter_branch_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='company',
        ),
        migrations.AddField(
            model_name='customuser',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='users', to='CRE.company'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='countries',
            field=models.ManyToManyField(blank=True, related_name='users', to='CRE.country'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='User assigned as the manager of this restaurant', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_restaurants', to=settings.AUTH_USER_MODEL),
        ),
    ]
