# Generated by Django 5.0.4 on 2024-12-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRE', '0007_remove_customuser_company_customuser_companies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionorstate',
            name='type',
            field=models.CharField(choices=[('region', 'Region'), ('state', 'State'), ('province', 'Province')], default='region', max_length=100),
        ),
    ]
