# Generated by Django 5.0.4 on 2025-05-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRE', '0008_shiftpattern_shiftpattern_at_least_one_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='r_val',
            field=models.PositiveIntegerField(default=12),
        ),
    ]
