# Generated by Django 5.0.4 on 2025-06-29 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRE', '0009_customuser_r_val'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffshift',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_shifts', to='CRE.branch'),
        ),
    ]
