# Generated by Django 5.0.4 on 2025-06-29 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRE', '0010_staffshift_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffshift',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_shifts', to='CRE.branch'),
        ),
        migrations.AlterField(
            model_name='staffshift',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staffshift',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
