# Generated by Django 5.0.4 on 2025-07-17 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRE', '0014_remove_menu_branches_remove_menu_restaurant_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together={('branch', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='menuitem',
            unique_together={('name', 'category')},
        ),
        migrations.CreateModel(
            name='SequenceCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_type', models.CharField(max_length=50)),
                ('max_digits', models.PositiveSmallIntegerField(default=4)),
                ('last_value', models.PositiveIntegerField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRE.branch')),
            ],
            options={
                'indexes': [models.Index(fields=['branch', 'sequence_type'], name='CRE_sequenc_branch__3e2f13_idx')],
                'unique_together': {('branch', 'sequence_type')},
            },
        ),
    ]
