# Generated by Django 5.0.4 on 2025-07-29 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRE', '0015_alter_menu_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='is_pos_menu',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='is_web_or_app_menu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='priority',
            field=models.IntegerField(default=0, help_text='Set priority in cook time'),
        ),
        migrations.AddField(
            model_name='shift',
            name='shift_leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_shifts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('web', 'Website'), ('app', 'Mobile App'), ('pos', 'POS Terminal'), ('kiosk', 'In-Store Kiosk')], default='pos', max_length=20, verbose_name='Source'),
        ),
    ]
