# Generated by Django 5.0.4 on 2025-08-01 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRE', '0016_menu_is_pos_menu_menu_is_web_or_app_menu_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='currency',
            field=models.CharField(choices=[('XAF', 'Central African CFA Franc'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('ZAR', 'South African Rand'), ('NGN', 'Nigerian Naira'), ('GHS', 'Ghanaian Cedi'), ('XOF', 'West African CFA Franc'), ('KES', 'Kenyan Shilling'), ('RWF', 'Rwandan Franc'), ('TND', 'Tunisian Dinar'), ('MAD', 'Moroccan Dirham')], default='XAF', max_length=3),
        ),
        migrations.AddField(
            model_name='branch',
            name='extension',
            field=models.CharField(choices=[('branch', 'In Branch'), ('kiosk', 'Station Kiosk'), ('food_truck', 'Food Truck')], default='branch', max_length=10),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['username'], name='CRE_customu_usernam_d7f6ec_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='CRE_customu_email_0abda3_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['phone_number'], name='CRE_customu_phone_n_7e12d8_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['status'], name='CRE_customu_status_e44f1c_idx'),
        ),
    ]
