# Generated by Django 5.0.4 on 2025-08-01 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRE', '0017_branch_currency_branch_extension_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='allow_auto_shift_swap',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ShiftSwapRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desired_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shiftswaps', to='CRE.branch')),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counterparty_swaps', to=settings.AUTH_USER_MODEL)),
                ('counterparty_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counterparty_swaps', to='CRE.shift')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_swaps', to=settings.AUTH_USER_MODEL)),
                ('initiator_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiator_swaps', to='CRE.shift')),
            ],
            options={
                'indexes': [models.Index(fields=['initiator', 'status'], name='CRE_shiftsw_initiat_494738_idx'), models.Index(fields=['counterparty', 'status'], name='CRE_shiftsw_counter_179b03_idx'), models.Index(fields=['desired_date'], name='CRE_shiftsw_desired_7ca2df_idx'), models.Index(fields=['accepted_at'], name='CRE_shiftsw_accepte_95ab42_idx')],
            },
        ),
    ]
