# Generated by Django 5.0.4 on 2025-08-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRE', '0019_order_cancelled_at_order_cancelled_by_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['r_val'], name='CRE_customu_r_val_422882_idx'),
        ),
    ]
