# Generated by Django 5.0.4 on 2025-08-05 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRE', '0020_customuser_cre_customu_r_val_422882_idx'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('permissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='branchpermissionassignment',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branchpermissionassignment',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='branchpermissionassignment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='active', max_length=10),
        ),
        migrations.AddIndex(
            model_name='branchpermissionassignment',
            index=models.Index(fields=['status'], name='permissions_status_d3738f_idx'),
        ),
    ]
