# Generated by Django 5.0.4 on 2025-07-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fixed amount for the rule', max_digits=12, null=True),
        ),
    ]
