# Generated by Django 5.0.4 on 2025-09-21 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cre', '0003_branch_logo_company_logo_restaurant_logo'),
        ('payroll', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='override',
            name='payroll_ove_user_id_089ab2_idx',
        ),
        migrations.RemoveIndex(
            model_name='override',
            name='payroll_ove_branch__f88da7_idx',
        ),
        migrations.RemoveIndex(
            model_name='record',
            name='payroll_rec_period__ddfe83_idx',
        ),
        migrations.RemoveIndex(
            model_name='rule',
            name='payroll_rul_scope_c95518_idx',
        ),
        migrations.AddField(
            model_name='record',
            name='bonus_details',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='record',
            name='deduction_details',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='override',
            name='period',
            field=models.ForeignKey(blank=True, help_text='Payroll period this override applies to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='payroll.period'),
        ),
        migrations.AddIndex(
            model_name='override',
            index=models.Index(fields=['rule'], name='payroll_ove_rule_id_1b25e2_idx'),
        ),
        migrations.AddIndex(
            model_name='override',
            index=models.Index(fields=['user'], name='payroll_ove_user_id_e107f2_idx'),
        ),
        migrations.AddIndex(
            model_name='override',
            index=models.Index(fields=['override_type'], name='payroll_ove_overrid_ab36ef_idx'),
        ),
        migrations.AddIndex(
            model_name='override',
            index=models.Index(fields=['effective_from', 'expires_at'], name='payroll_ove_effecti_d68c51_idx'),
        ),
        migrations.AddIndex(
            model_name='override',
            index=models.Index(fields=['branch'], name='payroll_ove_branch__437c57_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['period'], name='payroll_rec_period__aa83a0_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['branch'], name='payroll_rec_branch__a29f41_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['user'], name='payroll_rec_user_id_5dc904_idx'),
        ),
        migrations.AddIndex(
            model_name='rule',
            index=models.Index(fields=['scope'], name='payroll_rul_scope_d84f93_idx'),
        ),
        migrations.AddIndex(
            model_name='rule',
            index=models.Index(fields=['company'], name='payroll_rul_company_545033_idx'),
        ),
        migrations.AddIndex(
            model_name='rule',
            index=models.Index(fields=['restaurant'], name='payroll_rul_restaur_60f30c_idx'),
        ),
        migrations.AddIndex(
            model_name='rule',
            index=models.Index(fields=['branch'], name='payroll_rul_branch__57058a_idx'),
        ),
        migrations.AddIndex(
            model_name='rule',
            index=models.Index(fields=['is_active'], name='payroll_rul_is_acti_4a8533_idx'),
        ),
        migrations.AddIndex(
            model_name='rule',
            index=models.Index(fields=['effective_from'], name='payroll_rul_effecti_ad20e6_idx'),
        ),
    ]
