# Generated by Django 5.0.4 on 2025-09-21 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_remove_override_payroll_ove_user_id_089ab2_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='effectiverule',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='effectiverule',
            name='period',
        ),
        migrations.RemoveField(
            model_name='effectiverule',
            name='rule',
        ),
        migrations.RemoveField(
            model_name='effectiverule',
            name='user',
        ),
        migrations.DeleteModel(
            name='Component',
        ),
        migrations.DeleteModel(
            name='EffectiveRule',
        ),
    ]
