# Generated by Django 5.0.4 on 2025-09-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_remove_effectiverule_branch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='override',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='percentage',
        ),
        migrations.AlterField(
            model_name='override',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Override amount, if applicable', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='override',
            name='override_type',
            field=models.CharField(choices=[('replace', 'Replace'), ('add', 'Add'), ('subtract', 'Subtract')], help_text='Action: replace rule value, add to it, or remove the rule', max_length=20),
        ),
        migrations.AlterField(
            model_name='rule',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Fixed amount for the rule', max_digits=12, null=True),
        ),
    ]
