# Generated by Django 5.0.4 on 2025-09-29 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_remove_override_percentage_remove_rule_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='override',
            name='non_negative_override_percentage',
        ),
        migrations.RemoveConstraint(
            model_name='rule',
            name='non_negative_percentage',
        ),
    ]
