# Generated by Django 5.0.4 on 2025-08-09 14:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('company', 'Company'), ('restaurant', 'Restaurant'), ('branch', 'Branch')], max_length=50)),
                ('object_id', models.PositiveIntegerField()),
                ('object_map', models.JSONField(default=dict)),
                ('grace_period_expiry', models.DateTimeField()),
                ('deleted_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('reverted_at', models.DateTimeField(blank=True, null=True)),
                ('cleanup_task_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending Deletion'), ('deleted', 'Deleted'), ('reverted', 'Reverted')], default='pending_deletion', max_length=20)),
                ('migration_status', models.CharField(choices=[('not_migrated', 'Not Migrated'), ('migrated', 'Migrated'), ('failed', 'Failed')], default='not_migrated', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('company', 'Company'), ('restaurant', 'Restaurant'), ('branch', 'Branch')], max_length=50)),
                ('object_id', models.PositiveIntegerField()),
                ('action', models.CharField(max_length=50)),
                ('user_id', models.PositiveIntegerField(null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('details', models.TextField(blank=True)),
            ],
        ),
    ]
