# Generated by Django 5.0.4 on 2025-04-25 16:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('company', 'Company'), ('restaurant', 'Restaurant'), ('branch', 'Branch')], max_length=50)),
                ('object_id', models.PositiveIntegerField()),
                ('grace_period_expiry', models.DateTimeField()),
                ('deleted_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('reverted_at', models.DateTimeField()),
                ('cleanup_task_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending Deletion'), ('deleted', 'Deleted'), ('reverted', 'Reverted')], default='pending_deletion', max_length=20)),
                ('migration_status', models.CharField(choices=[('not_migrated', 'Not Migrated'), ('migrated', 'Migrated'), ('failed', 'Failed')], default='not_migrated', max_length=20)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_objects', to=settings.AUTH_USER_MODEL)),
                ('reverted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverted_objects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('company', 'Company'), ('restaurant', 'Restaurant'), ('branch', 'Branch')], max_length=50)),
                ('object_id', models.PositiveIntegerField()),
                ('action', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('details', models.TextField(blank=True)),
                ('deleted_object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='archive.deletedobject')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='object_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='deletedobject',
            index=models.Index(fields=['object_type', 'object_id'], name='archive_del_object__655c85_idx'),
        ),
        migrations.AddIndex(
            model_name='deletedobject',
            index=models.Index(fields=['status', 'migration_status'], name='archive_del_status_682d53_idx'),
        ),
        migrations.AddIndex(
            model_name='objecthistory',
            index=models.Index(fields=['object_type', 'object_id'], name='archive_obj_object__078be0_idx'),
        ),
        migrations.AddIndex(
            model_name='objecthistory',
            index=models.Index(fields=['timestamp'], name='archive_obj_timesta_97c6d2_idx'),
        ),
    ]
