# Generated by Django 5.0.4 on 2025-04-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletedobject',
            name='object_graph',
            field=models.JSONField(default=dict),  # Or use null=True if preferred
        ),
    ]
