# Generated by Django 5.0.4 on 2025-08-09 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('archive', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deletedobject',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deletedobject',
            name='reverted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverted_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='objecthistory',
            name='deleted_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='archive.deletedobject'),
        ),
        migrations.AddIndex(
            model_name='deletedobject',
            index=models.Index(fields=['object_type', 'object_id'], name='archive_del_object__655c85_idx'),
        ),
        migrations.AddIndex(
            model_name='deletedobject',
            index=models.Index(fields=['status', 'migration_status'], name='archive_del_status_682d53_idx'),
        ),
        migrations.AddIndex(
            model_name='objecthistory',
            index=models.Index(fields=['object_type', 'object_id'], name='archive_obj_object__078be0_idx'),
        ),
        migrations.AddIndex(
            model_name='objecthistory',
            index=models.Index(fields=['timestamp'], name='archive_obj_timesta_97c6d2_idx'),
        ),
    ]
