# Generated by Django 5.0.4 on 2025-04-25 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_auto_20250425_2152'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deletedobject',
            name='object_graph',
        ),
        migrations.AlterField(
            model_name='deletedobject',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deletedobject',
            name='reverted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverted_objects', to=settings.AUTH_USER_MODEL),
        ),
    ]
