# Generated by Django 5.0.4 on 2025-05-01 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0003_remove_deletedobject_object_graph_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='deletedobject',
            name='archive_del_object__655c85_idx',
        ),
        migrations.RemoveIndex(
            model_name='deletedobject',
            name='archive_del_status_682d53_idx',
        ),
        migrations.RemoveField(
            model_name='deletedobject',
            name='migration_status',
        ),
    ]
