# Generated by Django 5.0.4 on 2025-05-01 06:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0004_remove_deletedobject_archive_del_object__655c85_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deletedobject',
            name='migration_status',
            field=models.CharField(choices=[('not_migrated', 'Not Migrated'), ('migrated', 'Migrated'), ('failed', 'Failed')], default='not_migrated', max_length=20),
        ),
        migrations.AddIndex(
            model_name='deletedobject',
            index=models.Index(fields=['object_type', 'object_id'], name='archive_del_object__655c85_idx'),
        ),
        migrations.AddIndex(
            model_name='deletedobject',
            index=models.Index(fields=['status', 'migration_status'], name='archive_del_status_682d53_idx'),
        ),
    ]
