# Generated by Django 5.0.4 on 2025-05-01 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0005_deletedobject_migration_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletedobject',
            name='object_map',
            field=models.JSONField(default=dict),
        ),
    ]
