# Generated by Django 5.0.4 on 2025-05-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0006_deletedobject_object_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletedobject',
            name='reverted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
