# Generated by Django 5.0.4 on 2025-05-01 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0007_alter_deletedobject_reverted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objecthistory',
            name='user',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
