# Generated by Django 5.0.4 on 2025-05-01 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0008_alter_objecthistory_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objecthistory',
            old_name='user',
            new_name='user_id',
        ),
    ]
