# Generated by Django 5.0.4 on 2025-09-29 23:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('coupon_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Coupon ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('effect_type', models.CharField(choices=[('discount_percentage', 'Discount Percentage'), ('discount_fixed', 'Fixed Amount Discount'), ('credit_addition', 'Credit Addition'), ('trial_extension', 'Trial Extension'), ('free_feature', 'Free Feature'), ('bundle_discount', 'Bundle Discount')], max_length=20, verbose_name='Effect Type')),
                ('coupon_metadata', models.JSONField(blank=True, default=dict, verbose_name='Coupon Metadata')),
                ('discount_type', models.CharField(blank=True, choices=[('percentage', 'Percentage'), ('fixed_amount', 'Fixed Amount')], max_length=20, null=True, verbose_name='Discount Type')),
                ('discount_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Discount Value')),
                ('max_uses', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Max Uses')),
                ('max_uses_per_entity', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Max Uses Per Entity')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End Date')),
                ('applies_to_entity_type', models.CharField(choices=[('company', 'Company'), ('restaurant', 'Restaurant'), ('branch', 'Branch'), ('any', 'Any')], default='any', max_length=20, verbose_name='Applies to Entity Type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('subscription_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Subscription ID')),
                ('entity_type', models.CharField(choices=[('company', 'Company'), ('restaurant', 'Restaurant'), ('branch', 'Branch'), ('any', 'Any')], max_length=20, verbose_name='Entity Type')),
                ('entity_id', models.IntegerField(verbose_name='Entity ID')),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('grace_period', 'Grace Period'), ('suspended', 'Suspended'), ('canceled', 'Canceled')], max_length=20, verbose_name='Status')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Date')),
                ('trial_end_date', models.DateTimeField(blank=True, null=True, verbose_name='Trial End Date')),
                ('current_period_start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Current Period Start')),
                ('current_period_end', models.DateTimeField(blank=True, null=True, verbose_name='Current Period End')),
                ('auto_renew', models.BooleanField(default=True, verbose_name='Auto Renew')),
                ('cancel_at_period_end', models.BooleanField(default=False, verbose_name='Cancel at Period End')),
                ('balance', models.IntegerField(default=0, verbose_name='Balance')),
                ('plan_name', models.CharField(max_length=100, verbose_name='Plan Name')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
            },
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('redemption_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Redemption ID')),
                ('entity_type', models.CharField(choices=[('company', 'Company'), ('restaurant', 'Restaurant'), ('branch', 'Branch'), ('any', 'Any')], max_length=20, verbose_name='Entity Type')),
                ('entity_id', models.IntegerField(verbose_name='Entity ID')),
                ('effect_applied', models.JSONField(blank=True, default=dict, verbose_name='Effect Applied')),
                ('redeemed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Redeemed At')),
                ('discount_applied', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Discount Applied')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='subscriptions.coupon', verbose_name='Coupon')),
            ],
            options={
                'verbose_name': 'Coupon Redemption',
                'verbose_name_plural': 'Coupon Redemptions',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('feature_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Feature ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
                'indexes': [models.Index(fields=['is_active'], name='idx_feature_is_active')],
            },
        ),
        migrations.AddField(
            model_name='coupon',
            name='applies_to_feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.feature', verbose_name='Applies to Feature'),
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='History ID')),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('renewed', 'Renewed'), ('canceled', 'Canceled'), ('plan_changed', 'Plan Changed'), ('status_changed', 'Status Changed'), ('feature_added', 'Feature Added'), ('feature_removed', 'Feature Removed'), ('plan_created', 'Plan Created'), ('plan_updated', 'Plan Updated'), ('plan_deleted', 'Plan Deleted'), ('feature_created', 'Feature Created'), ('feature_updated', 'Feature Updated'), ('feature_deleted', 'Feature Deleted'), ('coupon_created', 'Coupon Created'), ('coupon_updated', 'Coupon Updated'), ('coupon_deleted', 'Coupon Deleted'), ('coupon_redeemed', 'Coupon Redeemed')], max_length=50, verbose_name='Event Type')),
                ('old_status', models.CharField(blank=True, choices=[('trial', 'Trial'), ('active', 'Active'), ('grace_period', 'Grace Period'), ('suspended', 'Suspended'), ('canceled', 'Canceled')], max_length=20, null=True, verbose_name='Old Status')),
                ('new_status', models.CharField(blank=True, choices=[('trial', 'Trial'), ('active', 'Active'), ('grace_period', 'Grace Period'), ('suspended', 'Suspended'), ('canceled', 'Canceled')], max_length=20, null=True, verbose_name='New Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('new_feature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_feature_history', to='subscriptions.feature', verbose_name='New Feature')),
                ('old_feature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_feature_history', to='subscriptions.feature', verbose_name='Old Feature')),
            ],
            options={
                'verbose_name': 'Subscription History',
                'verbose_name_plural': 'Subscription Histories',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('plan_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Plan ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('billing_type', models.CharField(choices=[('monthly_fixed', 'Monthly Fixed'), ('pay_per_order', 'Pay Per Order')], max_length=20, verbose_name='Billing Type')),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monthly Price')),
                ('included_credits', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Included Credits')),
                ('grace_credits', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Grace Credits')),
                ('grace_days', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Grace Days')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
                'indexes': [models.Index(fields=['is_active'], name='idx_plan_is_active')],
            },
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('billing_type', 'monthly_fixed'), ('included_credits__isnull', True), ('monthly_price__isnull', False)), models.Q(('billing_type', 'pay_per_order'), ('included_credits__isnull', False), ('monthly_price__isnull', True)), _connector='OR'), name='valid_pricing'),
        ),
        migrations.AddField(
            model_name='history',
            name='new_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_plan_history', to='subscriptions.plan', verbose_name='New Plan'),
        ),
        migrations.AddField(
            model_name='history',
            name='old_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_plan_history', to='subscriptions.plan', verbose_name='Old Plan'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='applies_to_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.plan', verbose_name='Applies to Plan'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='features',
            field=models.ManyToManyField(related_name='subscriptions', to='subscriptions.feature', verbose_name='Features'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='subscriptions.plan', verbose_name='Plan'),
        ),
        migrations.AddField(
            model_name='history',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.subscription', verbose_name='Subscription'),
        ),
        migrations.AddField(
            model_name='couponredemption',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.subscription', verbose_name='Subscription'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['code'], name='idx_coupon_code'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['is_active'], name='idx_coupon_is_active'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['entity_type', 'entity_id'], name='idx_subscription_entity'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status'], name='idx_subscription_status'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['plan'], name='idx_subscription_plan_id'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['current_period_start', 'current_period_end'], name='idx_subscription_period'),
        ),
        migrations.AddIndex(
            model_name='history',
            index=models.Index(fields=['subscription'], name='idx_history_subscription_id'),
        ),
        migrations.AddIndex(
            model_name='history',
            index=models.Index(fields=['created_at'], name='idx_history_created_at'),
        ),
        migrations.AddIndex(
            model_name='couponredemption',
            index=models.Index(fields=['subscription'], name='idx_coupon_subscription_id'),
        ),
        migrations.AddIndex(
            model_name='couponredemption',
            index=models.Index(fields=['coupon'], name='idx_coupon_coupon_id'),
        ),
        migrations.AddIndex(
            model_name='couponredemption',
            index=models.Index(fields=['entity_type', 'entity_id'], name='idx_redemption_entity'),
        ),
    ]
