# Generated by Django 5.0.4 on 2025-09-29 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='plan',
            name='valid_pricing',
        ),
    ]
