# Generated by Django 5.0.4 on 2025-09-29 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_remove_plan_valid_pricing'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('billing_type', 'monthly_fixed'), ('included_credits__gte', 0), ('monthly_price__gt', 0)), models.Q(('billing_type', 'pay_per_order'), ('included_credits__gt', 0), ('monthly_price__gte', 0)), _connector='OR'), name='valid_pricing'),
        ),
    ]
