# Generated by Django 5.0.4 on 2025-09-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_plan_valid_pricing'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='plan',
            name='valid_pricing',
        ),
        migrations.AlterField(
            model_name='history',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='billing_type',
            field=models.CharField(choices=[('monthly_fixed', 'Monthly Fixed'), ('pay_per_order', 'Pay Per Order'), ('yearly_fixed', 'Yearly Fixed')], max_length=20, verbose_name='Billing Type'),
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('billing_type', 'monthly_fixed'), ('included_credits__gte', 0), ('monthly_price__gt', 0)), models.Q(('billing_type', 'pay_per_order'), ('included_credits__gt', 0), ('monthly_price__gte', 0)), models.Q(('billing_type', 'yearly_fixed'), ('included_credits__gte', 0), ('monthly_price__gt', 0)), _connector='OR'), name='valid_pricing'),
        ),
    ]
