# Generated by Django 5.0.4 on 2025-09-30 19:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_remove_plan_valid_pricing_alter_history_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='trial_days',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Trial Days'),
        ),
    ]
