# Generated by Django 5.0.4 on 2025-09-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0002_alter_device_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
