# Generated by Django 5.0.4 on 2025-09-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0003_device_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='fingerprint',
            field=models.CharField(default='xyz', max_length=256, unique=True),
            preserve_default=False,
        ),
    ]
