# Generated by Django 5.0.4 on 2025-09-09 18:26

import printing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0004_printer_fingerprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.CharField(default=printing.models.generate_device_id, max_length=12, unique=True),
        ),
    ]
