# Generated by Django 5.0.4 on 2025-03-04 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CRE', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_type', models.CharField(choices=[('kitchen', 'Kitchen'), ('service', 'Service'), ('management', 'Management')], max_length=20)),
                ('active_connections', models.PositiveIntegerField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRE.branch')),
            ],
        ),
        migrations.CreateModel(
            name='BranchActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('order_create', 'Order Created'), ('order_modify', 'Order Modified'), ('task_claim', 'Task Claimed'), ('task_complete', 'Task Completed'), ('payment_process', 'Payment Processed'), ('staff_available', 'Staff Availability Changed'), ('escalation', 'Task Escalated')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRE.branch')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['-timestamp'], name='notificatio_timesta_190850_idx'), models.Index(fields=['activity_type'], name='notificatio_activit_741809_idx')],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('prepare', 'Prepare Order'), ('serve', 'Serve Order'), ('payment', 'Process Payment')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('claimed', 'Claimed'), ('completed', 'Completed'), ('escalated', 'Escalated')], max_length=20)),
                ('preparation_time', models.DurationField(blank=True, null=True)),
                ('version', models.IntegerField(default=0)),
                ('timeout_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRE.order')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'task_type'], name='notificatio_status_697f3c_idx'), models.Index(fields=['timeout_at'], name='notificatio_timeout_4f29ab_idx')],
            },
        ),
    ]
