# Generated by Django 5.0.4 on 2025-03-20 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRE', '0004_alter_customuser_status'),
        ('notifications', '0002_employeetransfer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.CharField(choices=[('temporary', 'Temporary'), ('permanent', 'Permanent')], max_length=10, verbose_name='Transfer Type')),
                ('from_entity', models.CharField(max_length=100, verbose_name='From Entity')),
                ('to_entity', models.CharField(max_length=100, verbose_name='To Entity')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=10, verbose_name='Status')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End Date')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_history', to='CRE.branch', verbose_name='Branch')),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_transfer_history', to=settings.AUTH_USER_MODEL, verbose_name='Initiated By')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_history', to='CRE.restaurant', verbose_name='Restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_history', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Transfer History',
                'verbose_name_plural': 'Transfer Histories',
                'indexes': [models.Index(fields=['user', 'timestamp'], name='notificatio_user_id_9a78dd_idx'), models.Index(fields=['branch', 'timestamp'], name='notificatio_branch__5bed60_idx'), models.Index(fields=['restaurant', 'timestamp'], name='notificatio_restaur_b13958_idx')],
            },
        ),
    ]
