# Generated by Django 5.0.4 on 2025-04-03 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRE', '0004_alter_customuser_status'),
        ('notifications', '0003_transferhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchactivity',
            name='activity_type',
            field=models.CharField(choices=[('order_create', 'Order Created'), ('order_modify', 'Order Modified'), ('task_claim', 'Task Claimed'), ('task_complete', 'Task Completed'), ('payment_process', 'Payment Processed'), ('staff_available', 'Staff Availability Changed'), ('escalation', 'Task Escalated'), ('field_update', 'Update Field'), ('payment_processed', 'Payment Processed'), ('refund_issued', 'Refund Issued'), ('discount_applied', 'Discount Applied'), ('expense_logged', 'Expense Recorded'), ('reservation', 'Reservation Made'), ('complaint', 'Customer Complaint'), ('allergy_alert', 'Allergy Alert Recorded'), ('menu_update', 'Menu Updated'), ('item_add', 'Menu Item Added'), ('item_remove', 'Menu Item Removed'), ('price_change', 'Price Changed')], max_length=20),
        ),
        migrations.CreateModel(
            name='RestaurantActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('manager_assign', 'Manager Assigned'), ('manager_remove', 'Manager Removed'), ('staff_hire', 'Staff Hired'), ('staff_terminate', 'Staff Terminated'), ('shift_change', 'Shift Schedule Changed'), ('role_change', 'Staff Role Changed'), ('field_update', 'Update Field'), ('hours_change', 'Operating Hours Changed'), ('closure', 'Restaurant Closed'), ('reopen', 'Restaurant Reopened'), ('maintenance', 'Maintenance Performed'), ('equipment_failure', 'Equipment Failure'), ('health_inspection', 'Health Inspection')], max_length=20, verbose_name='Activity Type')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('details', models.JSONField(default=dict, verbose_name='Details')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRE.restaurant', verbose_name='Restaurant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_activities', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Restaurant Activity Log',
                'verbose_name_plural': 'Restaurant Activity Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='notificatio_timesta_d30ee1_idx'), models.Index(fields=['activity_type'], name='notificatio_activit_fdaad0_idx'), models.Index(fields=['restaurant', '-timestamp'], name='notificatio_restaur_15bdbf_idx'), models.Index(fields=['user', '-timestamp'], name='notificatio_user_id_e740b5_idx')],
            },
        ),
    ]
