# Generated by Django 5.0.4 on 2025-04-03 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRE', '0004_alter_customuser_status'),
        ('notifications', '0005_alter_branchactivity_activity_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchactivity',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CRE.branch'),
        ),
        migrations.AlterField(
            model_name='branchactivity',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='restaurantactivity',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CRE.restaurant', verbose_name='Restaurant'),
        ),
    ]
