# Generated by Django 5.0.4 on 2025-07-06 06:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRE', '0013_alter_shiftpattern_roles_alter_shiftpattern_users'),
        ('notifications', '0008_shiftassignmentlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shiftassignmentlog',
            unique_together={('branch', 'user', 'date')},
        ),
        migrations.AddField(
            model_name='shiftassignmentlog',
            name='action',
            field=models.CharField(default='assign', max_length=100, verbose_name='Shift Action'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='shiftassignmentlog',
            index=models.Index(fields=['branch', 'user', 'date'], name='shift_log_idx'),
        ),
        migrations.RemoveField(
            model_name='shiftassignmentlog',
            name='pattern',
        ),
    ]
