# Generated by Django 5.0.4 on 2025-07-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_alter_shiftassignmentlog_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
