# Generated by Django 5.0.4 on 2025-07-26 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRE', '0015_alter_menu_unique_together_and_more'),
        ('notifications', '0010_task_claimed_at_task_completed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='task',
            name='notificatio_timeout_4f29ab_idx',
        ),
        migrations.AlterField(
            model_name='task',
            name='claimed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='CRE.order'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['claimed_by', 'order_id'], name='notificatio_claimed_e7da78_idx'),
        ),
    ]
